theme: minima
title: Unpublished writing

author: Veronica Olivotto
email: veronica.olivotto@gmail.com

description: I am a researcher passionate about using mix-methods to understand and integrate the lived experiences, perceptions and actions of residents living in coastal and riverine areas affected by flooding and sea level rise into decision making, advocacy strategies and planning for adaptation programs and policies.
description: <a href: "https://www.linkedin.com/in/veronica-olivotto-phd-927b0a5/">Fnd me on LinkeDIn</a>
